name: Integration Candidate Bundle Generation

# Generate Integration Candidate branch for this repository.

on:
  workflow_dispatch:
    inputs:
      pr_nums:
        description: 'The pull request numbers to include. Comma separated'
        required: true
        type: string

jobs:
  generate-ic-bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout IC Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          ref: main
      - name: Configure Local Repository
        run: |
          gitconfigfile="[core]
            repositoryformatversion = 0
            filemode = true
            bare = false
            logallrefupdates = true
          [remote "origin"]
            url = https://github.com/dzbaker/cFE
            fetch = +refs/heads/*:refs/remotes/origin/*
          [remote "origin"]
            fetch = +refs/pull/*:refs/remotes/origin/pull/
            gh-resolved = base
          [gc]
            auto = 0
          [http "https://github.com/"]
            extraheader = AUTHORIZATION: basic ***
          [branch "main"]
            remote = origin
            merge = refs/heads/main" > .git/config
          echo "$gitconfigfile" > .git/config
          less .git/config
      - name: Rebase IC Branch
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git pull
          git checkout integration-candidate
          git rebase main
      - name: Merge each PR
        run: |
          prs=$(echo ${{ inputs.pr_nums }} | tr "," "\n")
          for pr in $prs
          do
              git merge origin/pull/$pr/head --no-ff -m "Merge pull request #$pr from branch\n\nmessage"
          done
