name: Integration Candidate Bundle Generation

# Generate Integration Candidate branch for this repository.

on:
  workflow_dispatch:
    inputs:
      pr_nums:
        description: 'The pull request numbers to include. Comma separated'
        required: true
        type: string

jobs:
  generate-ic-bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout IC Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          ref: main
      - name: Configure Local Repository
        run: |
          gitconfigfile="[core]\n\trepositoryformatversion = 0\n\tfilemode \
           = true\n\tbare = false\n\tlogallrefupdates = true\n[remote "origin"]\n\turl \
           = https://github.com/dzbaker/cFE\n\tfetch = +refs/heads/*:refs/remotes/origin/*\n[remote \
           "origin"]\n\tfetch = +refs/pull/*:refs/remotes/origin/pull/*\n\tgh-resolved = \
           base\n[gc]\n\tauto = 0\n[http "https://github.com/"]\n\textraheader = AUTHORIZATION: \
           basic ***\n[branch "main"]\n\tremote = origin\n\tmerge = refs/heads/main" > .git/config
           echo $gitconfigfile > .git/config
          less .git/config
      - name: Rebase IC Branch
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git pull
          git checkout integration-candidate
          git rebase main
      - name: Merge each PR
        run: |
          prs=$(echo ${{ inputs.pr_nums }} | tr "," "\n")
          for pr in $prs
          do
              git merge origin/pull/$pr/head --no-ff -m "Merge pull request #$pr from branch\n\nmessage"
          done
