name: Integration Candidate Bundle Generation

# Generate Integration Candidate branch for this repository.

on:
  workflow_dispatch:

jobs:
  generate-ic-bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout IC Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          ref: main
      - name: Rebase IC Branch
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git pull
          git checkout integration-candidate
          git rebase main
